import type { Metadata } from 'next';
// import { Inter } from 'next/font/google';
import { Manrope } from 'next/font/google';
import './globals.css';
import { SessionProvider } from 'next-auth/react';
import { Toaster } from 'react-hot-toast';
import { CartProvider } from '@/app/context/CartContext';
import Navbar from '@/components/NavBar'; 
import Footer from '@/components/Footer';
import { cn } from '@/lib/utils';

// const inter = Inter({ subsets: ['latin'] });
const manrope = Manrope({ subsets: ['latin'], variable: '--font-manrope' });


export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={cn(
                    'min-h-screen bg-background font-manrope antialiased',
                    manrope.variable
                )}>
        <SessionProvider>
          <CartProvider>
            <Navbar/>
            {children}
            <Footer/>
          </CartProvider>
        </SessionProvider>
        <Toaster />
      </body>
    </html>
  );
}
